config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :houses
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, :only => [:show, :index, :destroy, :edit, :update, :new, :create]
  resources :companies
  resources :searches
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
  end

  root to: 'home#index'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, :user_signed_in?,  only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @house = House.find(params[:id])
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    @house.companies_id = current_user.company_id
    @house.realtorcontact = current_user.email
    if @house.save
     flash[:success] = "House successfully added"
     redirect_to @house
    else
     render 'new'
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:location, :squareft, :yearbuilt, :style, :listprice, :floors, :basement, :currentowner, :realtorcontact, :potentialbuyers, :companies_id, :image)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, html: { multipart: true }, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :house_location %>
  </div>

  <div class="field">
    <%= form.label :square_ft %>
    <%= form.number_field :squareft, id: :house_squareft %>
  </div>

  <div class="field">
    <%= form.label :year_built %>
    <%= form.number_field :yearbuilt, id: :house_yearbuilt %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.select :style, ['Single family house', 'Apartment', 'Condo'] %>
  </div>

  <div class="field">
    <%= form.label :list_price %>
    <%= form.number_field :listprice, id: :house_listprice %>
  </div>

  <div class="field">
    <%= form.label :floors %>
    <%= form.number_field :floors, id: :house_floors %>
  </div>

  <div class="field">
    <%= form.label :basement %>
    <%= form.check_box :basement, id: :house_basement %>
  </div>

  <div class="field">
    <%= form.label :current_owner %>
    <%= form.text_field :currentowner, id: :house_currentowner %>
  </div>

  <div class="field">
    <%= form.label :potential_buyers %>
    <%= form.text_field :potentialbuyers, id: :house_potentialbuyers %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back to Houses', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>
<%= link_to "Custom Search", new_search_path%>

<br>
<br>

<table>
  <thead>
    <tr>
      <th> Location </th>
      <th> Squareft </th>
      <th> Yearbuilt </th>
      <th> Style </th>
      <th> Listprice </th>
      <th> Floors </th>
      <th> Basement </th>
      <th> Currentowner </th>
      <th> Realtorcontact </th>
      <th> Potentialbuyers </th>
      <th> Company </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.squareft %></td>
        <td><%= house.yearbuilt %></td>
        <td><%= house.style %></td>
        <td><%= house.listprice %></td>
        <td><%= house.floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.currentowner %></td>
        <td><%= house.realtorcontact %></td>
        <td><%= house.potentialbuyers %></td>
        <td><%= house.companies_id %></td>
        <td><%= link_to 'Show', house %></td>
        <% if (current_user.role_type=="Realtor" && current_user.company_id == house.companies_id) || current_user.admin? %>
          <td><%= link_to 'Edit', edit_house_path(house) %></td>
          <td><%= link_to 'Delete', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role_type == "realtor" || current_user.role_type=="Realtor" || current_user.admin? %>
  <%= link_to 'New House', new_house_path %> |
<% end %>
<br/>
<td><%= link_to 'Back to User page', users_url %></td>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back to Houses', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p>
  <strong>Squareft:</strong>
  <%= @house.squareft %>
</p>

<p>
  <strong>Yearbuilt:</strong>
  <%= @house.yearbuilt %>
</p>

<p>
  <strong>Style:</strong>
  <%= @house.style %>
</p>

<p>
  <strong>Listprice:</strong>
  <%= @house.listprice %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @house.floors %>
</p>

<p>
  <strong>Basement:</strong>
  <%= @house.basement %>
</p>

<p>
  <strong>Currentowner:</strong>
  <%= @house.currentowner %>
</p>

<p>
  <strong>Realtorcontact:</strong>
  <%= @house.realtorcontact %>
</p>

<p>
  <strong>Potentialbuyers:</strong>
  <%= @house.potentialbuyers %>
</p>

<p>
  <strong>Company ID:</strong>
  <%= @house.companies_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @house.image.url(:medium) %>
</p>

<%= link_to 'Back to Houses', houses_path %>