config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :houses
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, :only => [:show, :index, :destroy, :edit, :update, :new, :create]
  resources :companies
  resources :searches
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
  end

  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :company
  has_many :inquiries
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
         
  validates :name, presence: true
  validates :phone, numericality: { only_integer: true }, length: { in: 8..10}, allow_blank: true
  
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   
        user.uid = auth.uid
        user.provider = auth.provider
        user.role_type = 'Househunter'
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def index
    @users = User.all
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

 def create
   @user = User.new(user_params)
   if user.save
     flash[:success] = "User successfully added"
     redirect_to @user
   else
     render 'new'
     format.json { render json: @user.errors, status: :unprocessable_entity }
   end
 end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Details updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User successfully deleted"
    redirect_to users_url
  end
  #
  #def logged_in_user
  #  unless logged_in?
  #    flash[:danger] = "Please log in."
  #    redirect_to new_user_session_path
  #  end
  #end
  #    
  #def correct_user
  #  @user = User.find(params[:id])
  #  redirect_to(root_url) unless @user == current_user
  #end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation, :phone, :contact_type, :role_type, :company_id)
  end
    
  private
  
  # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :contact_type %><br />
    <%= f.select :contact_type, ['Phone', 'Text', 'Email']%>
  </div>
  
  <div class="field" id="userrole">
    <%= f.label :'User role' %><br />
    <%= f.select :role_type, ['Realtor', 'Househunter']%>
  </div>
  
  
  <%= f.label :company_id %>
  <%= select("user", "company_id", Company.all.collect{ |c| [ c.name, c.id] }) %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back to Users', users_path %>

app/views/users/index.html.erb
<% if !(current_user.provider == "facebook") %>
<%= link_to 'Change role/Edit profile', edit_user_registration_url %>
<% end %>

<br/>

<% if current_user.admin? %>
  <h1>Users section</h1>
  <table>
    <tr>
      <th>User name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if !user.admin? %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <td><%= link_to 'Create new user', new_user_url %></td>
<% end %>
<br/>
<br/>

<h1>Real estate companies section</h1>
<%= link_to 'View all real estate companies', companies_url %>

<br/>

<% if current_user.role_type == "realtor" || current_user.role_type == "Realtor"  || current_user.admin? %>
  <% Company.all.each do |company| %>
    <tr>
      <% if company.id == current_user.company_id %>
        <%= link_to 'View your real estate company details', (company) %>
      <% end %>
    </tr>
  <% end %>
  <br/>
<% end %>

<br/>

<h1>Houses section</h1>

<% if current_user.role_type == "realtor" || current_user.role_type == "Realtor"  || current_user.admin? %>
  <%= link_to 'View and list houses', houses_url %>
<% else %>
  <%= link_to 'View listed houses',houses_url %>
<% end %>

<br/>
<br/>

<h1>Inquiries</h1>
<% if current_user.role_type == "Househunter" %>
  <%= link_to 'View and Make an inquiry', inquiries_url %>
<% else %>
  <%= link_to 'View all enquiries', inquiries_url %>
<% end %>


<br/>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back to Users', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<p id="notice"><%= notice %></p>

<h2>Listing all users for admin functionalities only</h2>
    <table>
        <tr>
          <th>User name</th>
          <th>User phone</th>
          <th>User email</th>
          <th>User contact type</th>
          <th>User role</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

         <tr>
            <td><%= @user.name %></td>
            <td><%= @user.phone %></td>
            <td><%= @user.email %></td>
            <td><%= @user.contact_type %></td>
            <td><%= @user.role_type %></td>
        </tr>
    </table>
<%= link_to 'Back to Users', users_url %>
|