config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :houses
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, :only => [:show, :index, :destroy, :edit, :update, :new, :create]
  resources :companies
  resources :searches
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
  end

  root to: 'home#index'
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :website, presence: true, format: { with: /\A(http[s]?:\/\/)?([w]{3}[.])?[\w]+.[\w]+\z/ }
  validates :address, presence: true
  validates :year, allow_blank: true, numericality: { only_integer: true }, length: { is: 4 }
  validates :revenue, allow_blank: true, numericality: { only_integer: true }
  validates :synopsis, presence: true, allow_blank: true
  
  has_many :user, foreign_key: true
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  before_action :user_signed_in?

  def index
    @companies = Company.all
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
     flash[:success] = "Company successfully added"
     redirect_to @company
    else
     render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update_attributes(company_params)
      redirect_to company_path(@company), notice: "Company Updated!"
    else
      @errors = @company.errors.full_messages
      render :edit
    end
  end

  def destroy
    Company.find(params[:id]).destroy
    redirect_to companies_path, notice: "Deleted Company"
  end

  private

  def company_params
    params.require(:company).permit(:name, :website, :address, :year, :revenue, :size, :synopsis)
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  
  <div class="field">
    <%= f.label :'Year founded' %><br />
    <%= f.text_field :year %>
  </div>
  
  <div class="field">
    <%= f.label :'Company revenue' %><br />
    <%= f.text_field :revenue %>
  </div>

  <div class="field">
    <%= f.label :'Company size' %>
    <%= f.select :size, ['1-50', '51-200', '201-500', '501-1000', '1000+']%>
  </div>
  
   <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_area :synopsis %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="title-container">
  <h1>Edit Company details</h1>
</div>

<%= render partial: "form" %>

<div>
  <ul class="company-actions">
    <li><%= link_to "Back to Companies", companies_path %></li>
  </ul>
</div>

app/views/companies/index.html.erb
<h1>Real estate companies section</h1>

  <table>
    <tr>
      <th>Company name</th>
      <th></th>
    </tr>

    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <% if current_user.admin? || (company.id == current_user.company.id && current_user.role_type == 'Realtor') %>
          <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <% if current_user.admin? && (company.id != 1)%>
            <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
<br/ >

<% if current_user.role_type == "Realtor" %>
  <td><%= link_to "View current user's company", company_url(current_user) %></td>
<% end %>

<% if current_user.admin? %>
  <td><%= link_to 'Create new company', new_company_url %></td>
<% end %>

<br/ >
<td><%= link_to 'Back to Users', users_url %></td>

app/views/companies/new.html.erb
<div class="title-container">
  <h1>New Real Estate Company</h1>
</div>

<%= render partial: "form" %>

<div>
  <ul class="company-actions">
    <li><%= link_to "Back to Companies", companies_path %></li>
  </ul>
</div>

app/views/companies/show.html.erb
<h2> Company Name: </h2>
<p><%= @company.name %></p>
<h2> Company ID: </h2>
<p><%= @company.id %></p>

<h2>Website:</h2>
<p><%= @company.website %></p>


<h2>Synopsis:</h2>
<p><%= @company.synopsis %></p>



<div>
  <ul class="company-actions">
    <li><%= link_to "Back to Companies", companies_path %></li>
  </ul>
</div>