config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :houses
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, :only => [:show, :index, :destroy, :edit, :update, :new, :create]
  resources :companies
  resources :searches
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
  end

  root to: 'home#index'
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry,:user_signed_in?, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.user_id = current_user.id
    @inquiry.user_email = current_user.email
    
    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    
    @inquiry = Inquiry.find(params[:id])
    @user = User.find_by email: @inquiry.user_email
    
    respond_to do |format|
      
      ReplyMailer.reply_email(@user.email).deliver!
      
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:user_id, :subject, :message, :realtor_email, :reply)
    end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry, local: true) do |form| %>
  <% if inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id, "User ID (Leave Blank)" %>
    <%= form.text_field :user_id, id: :inquiry_user_id %>
  </div>
  
  <div class="field">
    <%= form.label :realtor_email, "Choose Realtor"%>
    <%= form.collection_select :realtor_email, User.select("email").where(["role_type LIKE ?", "%Realtor%"]), :email, :email, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :inquiry_subject %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :inquiry_message %>
  </div>

  <%if current_user.role_type == "Realtor"%>
  <div class="field">
    <%= form.label :reply %>
    <%= form.text_field :reply, id: :inquiry_reply %>
  </div>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Subject</th>
      <th>Message</th>
      <th>User Email</th>
      <th>Realtor Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <% if (current_user.email == inquiry.realtor_email) || inquiry.user_id == current_user.id || current_user.admin?%>
        <tr>
          <td><%= inquiry.user_id %></td>
          <td><%= inquiry.subject %></td>
          <td><%= inquiry.message %></td>
          <td><%= inquiry.user_email %></td>
          <td><%= inquiry.realtor_email %></td>
          <td><%= link_to 'Show', inquiry %></td>
          <%if current_user.role_type == "Househunter"%>
          <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
          <% end %>
          
          <%if current_user.admin? || current_user.role_type == "Househunter"%>
          <td><%= link_to 'Delete', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          
          <%if current_user.role_type == "Realtor"%>
          <td><%= link_to 'Reply', edit_inquiry_path(inquiry) %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%if !(current_user.role_type == "Realtor")%>
<%= link_to 'New Inquiry', new_inquiry_path %>
<% end %>|
<td><%= link_to 'Back to User page', users_url %></td>

app/views/inquiries/new.html.erb
<h1>New Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @inquiry.user %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @inquiry.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @inquiry.message %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @inquiry.user_email %>
</p>

<p>
  <strong>Realtor Email:</strong>
  <%= @inquiry.realtor_email %>
</p>

<p>
  <strong>Realtor Reply:</strong>
  <%= @inquiry.reply %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>